services:
  scylladb:
    image: scylladb/scylla:2026.1
    container_name: scylladb
    ports:
      - "127.0.0.1:9042:9042"   # host migrator va host TB uchun
    volumes:
      - scylla-data:/var/lib/scylla
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10

volumes:
  scylla-data:
    name: thingsboard-scylla-data
