services:
  scylladb:
    image: scylladb/scylla:2026.1
    container_name: scylladb
    ports:
      - "127.0.0.1:9042:9042"   # host migrator uchun
    volumes:
      - scylla-data:/var/lib/scylla
    networks:
      - tb_net
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10

volumes:
  scylla-data:
    external: true
    name: tb_db_migrator_scylla-data

networks:
  tb_net:
    external: true
    name: tb_ce_new_default
